services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: storyblok
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  api:
    build: .
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql2://app:password@db:3306/storyblok
      - RAILS_ENV=development
    depends_on:
      - db

volumes:
  mysql_data:
  bundle_cache:
